### ISSUE TITLE
Separate Quiz from Regular Subjects

### ISSUE THREAD

**Issue by rakeshtembhurne** [rakeshtembhurne/otts#10]
Need to separate quiz from regular subject. There will be a special default board, class and subject for quiz. User can register separately for quiz and subjects.

**Comment by jitendrathakur** [comment]
I am starting work on this. cheers

**Comment by jitendrathakur** [comment]
this has been completed

**Comment by rakeshtembhurne** [comment]
@jitz31 Please commit to your repo and send pull request
